name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Deploy
        uses: nwtgck/actions-netlify@v1.4.0
        with:
          publish-dir: ./public
          access-token: ${{ secrets.NETLIFY_ACCESS_TOKEN }}