name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Deploy
        uses: nwtgck/actions-netlify@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: <Netlify Site ID>
          BUILD_COMMAND: npm run build
          PUBLISH_DIRECTORY: <build output directory>